apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: vote-app
spec:
  serviceAccountName: pipeline
  triggers:
    - name: vote-trigger
      bindings:
        - ref: vote-app
      template:
        ref: vote-app
